development:
  cloud_name: xxxxxxx
  api_key: 'xxxxxxx'
  api_secret: xxxxxxxx
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: xxxxxxx
  api_key: 'xxxxxxx'
  api_secret: xxxxxxxx
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: xxxxxxx
  api_key: 'xxxxxxx'
  api_secret: xxxxxxxx
  enhance_image_tag: true
  static_image_support: false
